apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sandra-main-app
  namespace: sandra-app
  labels:
    app: sandra-main-app
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sandra-main-app
  template:
    metadata:
      labels:
        app: sandra-main-app
    spec:
      containers:
      - name: sandra-main-container
        image: sandral17/python-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
